### ISSUE TITLE
There is no linuxkit.iso with fedora.

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1905] opened 2017-05-26 07:00 UTC
**Description**
But it exist for mac. So it is expected ? and Why?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rneugeba** [comment] 2017-05-26 07:02
I don't understand this issue? Could you please explain in more detail?

**Comment by yankunsam** [comment] 2017-05-26 07:11
When I run "moby build linukit.yml" on Fedora 25. There is no files named "linuxkit.iso " and "linuxkit-efi.iso". But "linuxkit run linuxkit" is well. 

But in mac, they exist.

sam-machinedeMacBook-Pro:linuxkit sam$ ls
AUTHORS             NOTICE              examples            linuxkit-kernel     poule.yml           src
CONTRIBUTING.md     README.md           kernel              linuxkit-state      projects            test
LICENSE             bin                 linuxkit-cmdline    linuxkit.iso        reports             tools
MAINTAINERS         blueprints          linuxkit-efi.iso    linuxkit.yml        scripts             vendor
Makefile            docs                linuxkit-initrd.img pkg                 sigs                vendor.conf
sam-machinedeMacBook-Pro:linuxkit sam$

**Comment by justincormack** [comment] 2017-05-26 07:39
Can you do moby -v build linuxkit.yml which should be more verbose

**Comment by yankunsam** [comment] 2017-05-26 08:31
I try it. But there is no error message. So ?

**Comment by rneugeba** [comment] 2017-05-26 08:57
could you provide the full output. Can't debug without it

**Comment by rneugeba** [comment] 2017-05-26 09:44
can't reproduce this. I have done:
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock fedora:25 /bin/bash
# install docker 17.05-ce client as per: https://docs.docker.com/engine/installation/linux/fedora/#install-from-a-package
% yum install -y git make
% git clone https://github.com/linuxkit/linuxkit && cd linuxkit
% make
% ./bin/moby build linuxkit.yml
Extract kernel image: linuxkit/kernel:4.9.x
Add init containers:
Process init image: linuxkit/init:cbd7ae748f0a082516501a3e914fa0c924ee941e
Process init image: linuxkit/runc:24dfe632ed3ff53a026ee3fac046fd544434e2d6
Process init image: linuxkit/containerd:f1130450206d4f64f0ddc13d15bb68435aa1ff61
Process init image: linuxkit/ca-certificates:4e9a83e890e6477dcd25029fc4f1ced61d0642f4
Add onboot containers:
  Create OCI config for linuxkit/sysctl:225c52c2d6f04a040663bac84cabf81825027f64
  Create OCI config for linuxkit/binfmt:603e5f064b3e8a64088c0fcf7a80d2783541ee1d
  Create OCI config for linuxkit/dhcpcd:ae03169274d19fe8841314fa5a6fea3c61adbf4e
Add service containers:
  Create OCI config for linuxkit/rngd:69f951ce2a3a9534dbbc7ba8119e1df4391f06c0
  Create OCI config for nginx:alpine
Add files:
  etc/docker/daemon.json
Create outputs:
  linuxkit-kernel linuxkit-initrd.img linuxkit-cmdline
  linuxkit.iso
  linuxkit-efi.iso
% ls -l
total 143752
-rw-r--r--  1 root root     2074 May 26 09:38 AUTHORS
-rw-r--r--  1 root root    11633 May 26 09:38 CONTRIBUTING.md
-rw-r--r--  1 root root    10765 May 26 09:38 LICENSE
-rw-r--r--  1 root root     1128 May 26 09:38 MAINTAINERS
-rw-r--r--  1 root root     2277 May 26 09:38 Makefile
-rw-r--r--  1 root root      558 May 26 09:38 NOTICE
-rw-r--r--  1 root root     5310 May 26 09:38 README.md
drwxr-xr-x  2 root root     4096 May 26 09:39 bin
drwxr-xr-x  2 root root     4096 May 26 09:38 blueprints
drwxr-xr-x  3 root root     4096 May 26 09:38 docs
drwxr-xr-x  2 root root     4096 May 26 09:38 examples
drwxr-xr-x  6 root root     4096 May 26 09:38 kernel
-rw-r--r--  1 root root       40 May 26 09:40 linuxkit-cmdline
-rw-r--r--  1 root root 49364992 May 26 09:40 linuxkit-efi.iso
-rw-r--r--  1 root root 40878979 May 26 09:40 linuxkit-initrd.img
-rw-r--r--  1 root root  7545424 May 26 09:40 linuxkit-kernel
-rw-r--r--  1 root root 49283072 May 26 09:40 linuxkit.iso
-rw-r--r--  1 root root     1199 May 26 09:38 linuxkit.yml
drwxr-xr-x 20 root root     4096 May 26 09:38 pkg
-rw-r--r--  1 root root      425 May 26 09:38 poule.yml
drwxr-xr-x 17 root root     4096 May 26 09:38 projects
drwxr-xr-x  3 root root     4096 May 26 09:38 reports
drwxr-xr-x  3 root root     4096 May 26 09:38 scripts
drwxr-xr-x  3 root root     4096 May 26 09:38 sigs
drwxr-xr-x  5 root root     4096 May 26 09:38 src
drwxr-xr-x  5 root root     4096 May 26 09:38 test
drwxr-xr-x 15 root root     4096 May 26 09:38 tools
drwxr-xr-x  6 root root     4096 May 26 09:38 vendor
-rw-r--r--  1 root root     1252 May 26 09:38 vendor.conf
```

Closing

**Closed by rneugeba** 2017-05-26 09:44 UTC

**Comment by yankunsam** [comment] 2017-05-26 09:49
Sorry. I do not add

-  - format: iso-bios
-  - format: iso-efi


so....

Thanks

**Comment by yankunsam** [comment] 2017-05-26 09:52
Another question:

When I use kvm to create a vm base linuxkit.iso. How to install it to a disk ?
