### ISSUE TITLE
coreos grub compile fails with Alpine 3.9 tool chain

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3295] opened 2019-03-02 19:05 UTC
While updating the alpine base to Alpine 3.9 the build of `mkimage-iso-efi`, `mkimage-qcow2-efi`, and `mkimage-raw-efi` fails on x86 and arm64 with the following warnings:
```
gcc -DHAVE_CONFIG_H -I.  -Wall -W -DGRUB_UTIL=1 -D_FILE_OFFSET_BITS=64 -I./include -DGRUB_FILE=\"grub-core/osdep/init.c\" -I. -I. -I. -I. -I./include -I./include -I./grub-core/lib/libgcrypt-grub/src/ -I./grub-core/gnulib -I./grub-core/gnulib  -D_FILE_OFFSET_BITS=64 -fno-builtin-gettext
 -Wall -W -Wshadow -Wpointer-arith -Wundef -Wchar-subscripts -Wcomment -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wfloat-equal -Wformat-extra-args -Wformat-security -Wformat-y2k -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wmain -Wmissing-braces -Wmi
ssing-format-attribute -Wmultichar -Wparentheses -Wreturn-type -Wsequence-point -Wshadow -Wsign-compare -Wswitch -Wtrigraphs -Wunknown-pragmas -Wunused -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value  -Wunused-variable -Wwrite-strings -Wnested-externs -Wstrict-protot
ypes -Wcast-align  -Wextra -Wattributes -Wendif-labels -Winit-self -Wint-to-pointer-cast -Winvalid-pch -Wmissing-field-initializers -Wnonnull -Woverflow -Wvla -Wpointer-to-int-cast -Wstrict-aliasing -Wvariadic-macros -Wvolatile-register-var -Wpointer-sign -Wmissing-include-dirs -Wmissi
ng-prototypes -Wmissing-declarations -Wformat=2 -Werror -Wno-undef -Wno-sign-compare -Wno-unused -Wno-unused-parameter -Wno-redundant-decls -Wno-unreachable-code -Wno-conversion  -Os -Wno-unused-value -MT grub-core/osdep/grub_script_check-init.o -MD -MP -MF grub-core/osdep/.deps-util/g
rub_script_check-init.Tpo -c -o grub-core/osdep/grub_script_check-init.o `test -f 'grub-core/osdep/init.c' || echo './'`grub-core/osdep/init.c
mv -f grub-core/osdep/.deps-util/libgrubkern_a-sleep.Tpo grub-core/osdep/.deps-util/libgrubkern_a-sleep.Po
In file included from grub-core/partmap/gpt.c:26:
./include/grub/gpt_partition.h:90:1: error: alignment 1 of 'struct grub_gpt_header' is less than 8 [-Werror=packed-not-aligned]
 } GRUB_PACKED;
 ^
./include/grub/gpt_partition.h:100:1: error: alignment 1 of 'struct grub_gpt_partentry' is less than 8 [-Werror=packed-not-aligned]
 } GRUB_PACKED;
 ^
./include/grub/gpt_partition.h:100:1: error: alignment 1 of 'struct grub_gpt_partentry' is less than 8 [-Werror=packed-not-aligned]
```

when disabling this warning by adding `-Wno-packed-not-aligned` to the `CFLAGS` the compile succeeds on arm64 but still fails on x86 with:

```
 ../build-aux/install-sh -c -d '/usr/local/share/info'
make[3]: Leaving directory '/grub/docs'
make[2]: Leaving directory '/grub/docs'
Making install in util/bash-completion.d
make[2]: Entering directory '/grub/util/bash-completion.d'
make[3]: Entering directory '/grub/util/bash-completion.d'
make[3]: Nothing to be done for 'install-exec-am'.
 ../../build-aux/install-sh -c -d '/usr/local/etc/bash_completion.d'
 /usr/bin/install -c -m 644 grub '/usr/local/etc/bash_completion.d'
make[3]: Leaving directory '/grub/util/bash-completion.d'
make[2]: Leaving directory '/grub/util/bash-completion.d'
make[1]: Leaving directory '/grub'
./grub-mkimage: error: relocation 0x4 is not implemented yet.
The command '/bin/sh -c mkdir /grub-lib &&   set -e &&   git clone https://github.com/coreos/grub.git &&   cd grub &&   git checkout -b grub-build ${GRUB_COMMIT} &&   ./autogen.sh &&   ./configure --libdir=/grub-lib --with-platform=efi CFLAGS="-Os -Wno-unused-value -Wno-packed-not-aligned" &&   make -j "$(getconf _NPROCESSORS_ONLN)" &&   make install &&   case $(uname -m) in   x86_64)     ./grub-mkimage -O x86_64-efi -d /grub-lib/grub/x86_64-efi -o /grub-lib/BOOTX64.EFI -p /EFI/BOOT ${GRUB_MODULES} linuxefi;     ;;   aarch64)     ./grub-mkimage -O arm64-efi -d /grub-lib/grub/arm64-efi -o /grub-lib/BOOTAA64.EFI -p /EFI/BOOT ${GRUB_MODULES};     ;;   esac' returned a non-zero code: 1
exit status 1
```

We should probably move off an unmaintained version of grub.

/cc @deitch @arm64b

**Comment by deitch** [comment] 2019-03-02 19:11
Of course, when we first did this, coreos actually was a company and this was maintained. :-)

Part of the issue IIRC was tpm support, but I’ll have to dig into my notes from then (if I can find them). Coreos was one of the key supporters of it at the time. I suspect we have new options since then. 

This’ll require some work. 

Personally, I’d like to see grub removed entirely and boot straight into the kernel as an EFI file. But that also is non trivial and has its own issues. 

I’ll dig into getting this fixed first, but it might be a week or two.

**Comment by rn** [comment] 2019-03-02 19:14
No worries, about the timeline. I just dumped this info here while I still had it in a history buffer. For now I'm just not updating these packages to alpine 3.9. Simple enough

**Comment by deitch** [comment] 2019-03-15 11:32
Well, this is interesting. See [this commit](http://git.savannah.gnu.org/cgit/grub.git/commit/?id=d6ca0a90cac78f40ea4a04ac6894784c5313cbe9) to the official grub2. Looks like Matthew Garrett, who was at CoreOS when they forked and added tpm to grub (and hence that repo), has been committing to and adding support for tpm to the official grub. 

Worth reaching out and asking him what the support status is. The primary reason we went with the CoreOS one was for tpm support. If it is in official grub, we can get rid of the whole thing here.

**Comment by deitch** [comment] 2019-03-15 11:46
Heh, did you look at the apk package source for grub on alpine? [here](https://github.com/linuxkit/linuxkit/issues/3295#issuecomment-468950947) it is, look at the very first file/patch. :-)

**Comment by deitch** [comment] 2019-03-15 11:50
Looks like the version of grub included in alpine 3.9 does _not_ include the tpm patches. Was hoping we could just use that (assuming that MG says it is up to date - I did look at the code and it appears correct, but I would rather trust him). Will see what is up, maybe ask Alpine to update it.

**Comment by deitch** [comment] 2019-03-15 11:55
Ah, because grub 2.02 is almost two years old. All of these patches were merged in the last half a year, but not part of a release quite yet.

**Comment by deitch** [comment] 2019-03-15 12:04
@rn , we now have 3 repos that build grub independently as part of multi-stage docker builds. All look something like:

```Dockerfile
FROM linuxkit/alpine:3683c9a66cd4da40bd7d6c7da599b2dcd738b559 AS grub-build
RUN apk add \

# ~40 lines of building grub
# ...
# ...

FROM linuxkit/alpine:3683c9a66cd4da40bd7d6c7da599b2dcd738b559 AS mirror
RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
# package installation

FROM scratch
WORKDIR /
COPY --from=mirror /out/ /
COPY --from=grub-build /grub-lib/BOOT*.EFI /usr/local/share/
COPY . .
# whatever the entrypoint should be
```

I am thinking of the following to simplify it.

First, create a completely separate package `linuxkit/grub` that encompasses the entire build. We continue to build the CoreOS based on until we are sure upstream grub supports it, then change it here. This not only builds grub, but actually runs `grub-mkimage` for all of our various platforms.

Second, just consume that package in the dockerfile, like:

```dockerfile
FROM linuxkit/grub:<somehash> AS grub-images
FROM linuxkit/alpine:3683c9a66cd4da40bd7d6c7da599b2dcd738b559 AS mirror
RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
# package installation

FROM scratch
WORKDIR /
COPY --from=mirror /out/ /
COPY --from=grub-build /grub-lib/<myarch>/BOOT*.EFI /usr/local/share/
COPY . .
# whatever the entrypoint should be
```

This doesn't completely solve the issue - we still need to fix the build issue and get away from abandoned grub source - but makes the packages cleaner and gives us one place to fix it.

Thoughts?

**Comment by rn** [comment] 2019-03-15 15:26
On option is to build a tar ball (or better a apk) in `tools/alpine` so that it is included in the alpine base. then we just install it where it is needed. We do this with `containerd`.

**Comment by deitch** [comment] 2019-03-16 16:57
I’m ok with that, but we shouldn’t call it “grub” since there is an official grub apk package. That one right now is 2.0.2, latest official release, which doesn’t include the last two years of updates. Eventually they will release 2.0.3 or 2.1.0 or whatever which will include it, and then we can deprecate our own and use the standard alpine packages. I expect that’ll be quite some time though. 

@rn link to our containerd compile and inclusion as an example please?

**Comment by rn** [comment] 2019-03-16 17:01
`tools/alpine/Dockerfile` compiles containerd and sticks it into the base (does not do an apk). for grub it depends if you just want to stick a tarball or something into the base or a apk. I don't have preference either way

**Comment by deitch** [comment] 2019-03-16 17:18
OK

**Comment by deitch** [comment] 2019-03-16 17:24
Now that I think about it, why _do_ we do it that way? I looked at the containerd build, and it works like this:

1. Build it all in `linuxkit/alpine` [here](https://github.com/linuxkit/linuxkit/blob/master/tools/alpine/Dockerfile#L55-L67) but don't make an apk out of it
2. Copy the binaries over from `linuxkit/alpine` into `linuxkit/containerd` Dockerfile [here](https://github.com/linuxkit/linuxkit/blob/master/pkg/containerd/Dockerfile#L15) which is the sole place it is consumed.

Why don't we actually just do the build in `linuxkit/containerd` Dockerfile multi-stage, since that is the only place that uses it? It seems like that would be cleaner.

I am thinking the same thing for grub. If the only place that would use the source is in (the soon to be created) `linuxkit/grub`, which would end with a bunch of images, what is the advantage of building it in `linuxkit/alpine`, finishing with binaries that then are copied to `linuxkit/grub`?

**Comment by rn** [comment] 2019-03-16 17:43
containerd and ctr are needed in multiple packages and they need to match, so we build them once and stick them into `linuxkit/alpine`.

creating linuxkit/grub would also work, but it would complicate the release process a bit if there are too many dependencies between images in `tools`. See `./docs/releasing.md` where we already have a bit of a annoying steps around the alpine alpine base and the others.

**Comment by deitch** [comment] 2019-03-16 17:48
> containerd and ctr are needed in multiple packages and they need to match, so we build them once and stick them into linuxkit/alpine

Ah, that makes sense.

> creating linuxkit/grub would also work, but it would complicate the release process a bit if there are too many dependencies between images in tools

Oh, yes, because then it would have multiple `FROM`, each with a potentially different hash. Messy.

OK, I see it. I am going to get it working locally as a separate `pkg/linuxkit/grub`, and then merge it into `linuxkit/alpine` as a PR, unless the 3.8 vs 3.9 issues make it impossible, in which case I will release it as `linuxkit/grub`. Goals here are (in descending order of priority):

1. Separate build into separate image from all of the `mkimage-*-efi`
2. Switch from abandoned `coreos/grub` to upstream grub. Confirmed yesterday that it is compatible and functional for EFI (not for BIOS, but we don't use it for BIOS anyways).
3. Merge it into `linuxkit/alpine`.

Hopefully all 3, but at the very least first 2.

**Comment by justincormack** [comment] 2019-03-16 17:57
I think it is preferable to have it as linuxkit/grub as its then much easier to modify to use a different version vs if it is in linuxkit/alpine which seems weird.

**Comment by deitch** [comment] 2019-03-16 18:01
Personally, I want the whole thing to go away, but we are dependent on official grub for that.

For now, I am building under `linuxkit/grub` just to solve 1 & 2. Let's start there, as it is the common path.

**Comment by rn** [comment] 2019-03-16 18:16
OK, let's have a `linuxkit/grub` but put it into `./tools/grub` as it is not a enduser package and more used for building images.

Next time I release (soon, hopefully) will take care to build the `grub` package before the `mkimage` packages.

**Comment by deitch** [comment] 2019-04-16 20:30
Let's leave this issue open as a tracking issue for building CoreOS grub off of `alpine:3.9`.

The issue appears to be differences between `gcc:6.x` (from `alpine:3.8`) and `gcc:8.x` (from `alpine:3.9`). There is a discussion from the grub mailing list from about a year ago about this, see [here](https://lists.gnu.org/archive/html/grub-devel/2018-03/msg00083.html). Unfortunately, it looks like their patch already was applied.

I am going to hunt this down, might take a bit of time.

**Comment by deitch** [comment] 2019-04-17 09:41
Ha! Someone fixed it already at the original repo. Merging in.

**Comment by deitch** [comment] 2019-04-17 11:41
And... it has other issues. I need to add a patch. This would be easier if I knew how to build `linuxefi` as a patch and could graft it onto the upstream grub, so in the future it just gets removed. Oh well.

**Closed** 2019-04-18 17:47 UTC
