### ISSUE TITLE
Not possible to build kernel module for linuxkit 4.14.x

### ISSUE THREAD

**Issue by rvdh** [linuxkit/linuxkit#3402] opened 2019-08-15 13:58 UTC
**Description**

Docker Desktop for Mac's Edge version has released on 12-08-2019 with LinuxKit kernel version 4.14.131. Previously, this was version 4.9.x.

Apparently one change between those versions is that the GCC plugin "RANDSTRUCT" is now being used when building kernel modules.

**Steps to reproduce the issue:**

We were using the following Dockerfile to add f2fs support to the hyperkit vm on MacOS:
```
ARG KERNEL_VERSION=4.9.125
FROM linuxkit/kernel:${KERNEL_VERSION} AS ksrc
# Extract headers and compile module
FROM linuxkit/alpine:86cd4f51b49fb9a078b50201d892a3c7973d48ec AS build
ARG KERNEL_VERSION=4.9.125
RUN apk add build-base elfutils-dev bc

COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar
WORKDIR /usr/src
ADD "https://github.com/linuxkit/linux/archive/v${KERNEL_VERSION}.tar.gz" /usr/src/v${KERNEL_VERSION}.tar.gz

RUN tar xzf v${KERNEL_VERSION}.tar.gz && \
    cp /usr/src/linux-headers-${KERNEL_VERSION}-linuxkit/.config /usr/src/linux-${KERNEL_VERSION}/ && \
    cp /usr/src/linux-headers-${KERNEL_VERSION}-linuxkit/Module.symvers /usr/src/linux-${KERNEL_VERSION}

WORKDIR /usr/src/linux-${KERNEL_VERSION}
RUN echo -e "CONFIG_F2FS_FS=m\nCONFIG_F2FS_STAT_FS=y\nCONFIG_F2FS_FS_XATTR=y\nCONFIG_F2FS_FS_POSIX_ACL=y" >> .config && \
    echo -e "CONFIG_F2FS_FS_SECURITY=n\nCONFIG_F2FS_CHECK_FS=n\nCONFIG_F2FS_FS_ENCRYPTION=n\nCONFIG_F2FS_IO_TRACE=n\nCONFIG_F2FS_FAULT_INJECTION=n" >> .config && \
    make oldconfig && make modules_prepare && make M=fs/f2fs

ADD /entrypoint.sh /entrypoint.sh
ENV ENV_KERNEL_VERSION=${KERNEL_VERSION}
ENTRYPOINT /entrypoint.sh ${ENV_KERNEL_VERSION}
```

The entrypoint script does an insert (insmod) of the kernel module (another script is used to determine if this is needed):
```
#!/usr/bin/env sh
# shellcheck disable=SC2039
set -eo pipefail

echo -n "Checking if f2fs module is currently loaded..."
if ! lsmod | grep -q f2fs; then
    echo " no."
    echo -n "Loading f2fs module..."
    insmod "/usr/src/linux-${1}/fs/f2fs/f2fs.ko"
    echo " done".
else
    echo " yes."
fi
```

This process fails since kernel 4.14.x is used. 

**Describe the results you received:**

Insmod returns a "Invalid module format" error because of the now mismatching magic versions:
```
[28557.894206] f2fs: version magic '4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_b861822d10584c02634ce440a3163d2070a1bb2fe8a6ef6b00518f8060fc9948' should be '4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314'
```

As far as  I know, there is currently no way of determining the seed that was used during the kernel build, so we cannot supply this to the module build to end up with the correct magic version. I've tried copying the files `/usr/src/linux-headers-4.14.131-linuxkit/scripts/gcc-plugins/randomize_layout_seed.h` and `/usr/src/linux-headers-4.14.131-linuxkit/include/generated/randomize_layout_hash.h`, but *these do not correspond to the currently released linuxkit kernel and version*. 

Without the seed, its impossible to compile the kernel module with a corresponding seed/hash as magic version.

**Describe the results you expected:**

Compiling a custom kernel module (*not* an external kernel module) should work as before, the same RANDSTRUCT plugin seed should be used. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment] 2019-08-15 14:05
The RANDSTRUCT seed is in the pushed `linuxkit/kernel` images see https://github.com/linuxkit/linuxkit/issues/3398 and https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#compiling-external-kernel-modules

It is not on the host by default as far as I know, so you will need to extract it from these images. As far as I know the Docker Desktop kernels are unmodified LinuxKit kernels now.

**Comment by rvdh** [comment] 2019-08-15 14:14
As I mentioned, I tried extracting the seed and hashed seed from the image but these do not correspond to the released linuxkit kernel and version (4.14.131). 

I'll verify this again just to be sure.

**Comment by rvdh** [comment] 2019-08-15 14:47
I checked with the following Dockerfile:
```
FROM linuxkit/kernel:4.14.131 AS ksrc
FROM linuxkit/alpine:86cd4f51b49fb9a078b50201d892a3c7973d48ec AS build

COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar
WORKDIR /usr/src
```
Then built and started it like so:
```
$ docker build -t linuxtest .
...
$ docker run -v /dev:/dev -v /lib/modules:/lib/modules -it --privileged --entrypoint=/bin/sh kerneltest
```
First I checked the version of the kernel currently running to verify it was indeed 4.14.131-linuxkit:
```
/usr/src # uname -a
Linux 210b4e138b42 4.14.131-linuxkit #1 SMP Fri Jul 19 12:31:17 UTC 2019 x86_64 Linux
```
Then I checked if the correct headers were unpacked:
```
/usr/src # ls -al
total 12
drwxr-xr-x    3 root     root          4096 Aug 15 14:24 .
drwxr-xr-x    1 root     root          4096 Aug 15 14:24 ..
drwxr-xr-x   24 root     root          4096 Aug 15 14:24 linux-headers-4.14.131-linuxkit
/usr/src # cd linux-headers-4.14.131-linuxkit/
```
Then I checked the magic version of a currently loaded module:
```
/usr/src/linux-headers-4.14.131-linuxkit # lsmod
Module                  Size  Used by    Not tainted
xfrm_user              36864  1
xfrm_algo              16384  1 xfrm_user
vmw_vsock_virtio_transport    16384 16
vmw_vsock_virtio_transport_common    24576  1 vmw_vsock_virtio_transport
vsock                  36864 22 vmw_vsock_virtio_transport,vmw_vsock_virtio_transport_common

/usr/src/linux-headers-4.14.131-linuxkit # modinfo vsock
filename:       /lib/modules/4.14.131-linuxkit/kernel/net/vmw_vsock/vsock.ko
author:         VMware, Inc.
description:    VMware Virtual Socket Family
license:        GPL v2
version:        1.0.2.0-k
srcversion:     752C8E5D5706B0F6F1A5EE4
depends:
intree:         Y
vermagic:       4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314
```
As you can see the hashed seed is `ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314`.

Then I checked what hashed seed was present in the unpacked linux-headers directory:
```
/usr/src/linux-headers-4.14.131-linuxkit # cat include/generated/randomize_layout_hash.h
#define RANDSTRUCT_HASHED_SEED "ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc"
```
This doesn't match the magic version of the loaded module.

For completeness, this is the actual seed:
```
/usr/src/linux-headers-4.14.131-linuxkit # cat scripts/gcc-plugins/randomize_layout_seed.h
const char *randstruct_seed = "a8203afaf64560b4370c8d8216b8ed13ba371dba7e975e633fb4a9461ec6ce22";
```
If we hash this seed, we indeed come to the same value as in the randomize_layout_hash.h file above:
```

/usr/src/linux-headers-4.14.131-linuxkit # echo -n "a8203afaf64560b4370c8d8216b8ed13ba371dba7e975e633fb4a9461ec6ce22" | sha256sum | c
ut -d" " -f1 | tr -d ' \n'
ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc
```

**Comment by rvdh** [comment] 2019-08-15 15:11
I've also done a compile of the f2fs module as per the opening post by downloading the linux kernel source, unpacking it etc:

```
/usr/src # cp linux-headers-4.14.131-linuxkit/.config linux-4.14.131-linuxkit/
/usr/src # cp linux-headers-4.14.131-linuxkit/Module.symvers linux-4.14.131-linuxkit/
/usr/src # cd linux-4.14.131-linuxkit/
/usr/src/linux-4.14.131-linuxkit # cp ../linux-headers-4.14.131-linuxkit/scripts/gcc-plugins/randomiz
e_layout_seed.h scripts/gcc-plugins/
/usr/src/linux-4.14.131-linuxkit # echo -e "CONFIG_F2FS_FS=m\nCONFIG_F2FS_STAT_FS=y\nCONFIG_F2FS_FS_X
ATTR=y\nCONFIG_F2FS_FS_POSIX_ACL=y" >> .config && \
>     echo -e "CONFIG_F2FS_FS_SECURITY=n\nCONFIG_F2FS_CHECK_FS=n\nCONFIG_F2FS_FS_ENCRYPTION=n\nCONFIG
_F2FS_IO_TRACE=n\nCONFIG_F2FS_FAULT_INJECTION=n" >> .config
/usr/src/linux-4.14.131-linuxkit # make oldconfig && make modules_prepare
...
/usr/src/linux-4.14.131-linuxkit # cp ../linux-headers-4.14.131-linuxkit/include/generated/randomize_
layout_hash.h include/generated/

/usr/src/linux-4.14.131-linuxkit # make M=fs/f2fs
...
  Building modules, stage 2.
  MODPOST 1 modules
  CC      fs/f2fs/f2fs.mod.o
  LD [M]  fs/f2fs/f2fs.ko
/usr/src/linux-4.14.131-linuxkit # modinfo fs/f2fs/f2fs.ko
filename:       fs/f2fs/f2fs.ko
author:         Samsung Electronics's Praesto Team
description:    Flash Friendly File System
license:        GPL
alias:          fs-f2fs
depends:
vermagic:       4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc
```
As you can see this now ended up with the hashed seed from the image, but not from the actually running kernel, resulting in this error when trying to insmod it:
```
# insmod fs/f2fs/f2fs.ko
insmod: can't insert 'fs/f2fs/f2fs.ko': invalid module format
# dmesg | tail -1
[ 2987.784113] f2fs: version magic '4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc' should be '4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314'
```

**Comment by singe** [comment] 2019-09-10 08:19
I came to open the exact same issue, and can confirm @rvdh's experience.

Using linutkit/kernel:4.14.131 I build modules with the following version magic:

"4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc"

However, the docker-desktop linuxkit modules have:
"4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314"

as their version magic.

Commands to reproduce:

```
> docker run --rm -v /lib/modules:/lib/modules alpine:3.10 modinfo slhc|grep vermagic
vermagic:       4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314```

```
> docker run --rm -v /lib/modules:/lib/modules singelet/linuxkit-mac80211_hwsim:4.14.131|grep vermagic|head -n1
insmod: can't insert '/kmod//cfg80211.ko': Operation not permitted
vermagic:       4.14.131-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ee296308985f1a938bc6cf6db330ad5f6b4bf69ef19a9d14052f153c0774ecfc
```

**Comment by djs55** [comment] 2019-09-10 10:17
Unfortunately for 4.14 Docker Desktop switched (hopefully temporarily) to a tweaked kernel configuration, building `AF_VSOCK` as a module to work around the bug described in #3376, see https://github.com/linuxkit/linuxkit/pull/3407

**Comment by justincormack** [comment] 2019-09-10 10:29
@djs55 you should make your kernel source images available if you modify the kernel, as it is GPL licensed.

**Comment by singe** [comment] 2019-09-10 11:46
@djs55 Thanks. Would it be possible to use the randstruct seed from the published linuxkit/kernel image e.g. like I did in https://github.com/singe/linuxkit-mac80211_hwsim/blob/master/Dockerfile#L52 so it maintains the randstruct and we can build kernel modules without you needing to share your tweaked config. This should also "future proofs" against the same problem in the future.

Alternatively, could the linuxkit/kernel image be updated to the tweaked version you're using while you're using it?

Or lastly, could you publish a docker-desktop/kernel image of the same structure as the linuxkit/kernel image?

**Comment by djs55** [comment] 2019-09-10 15:32
@singe you should now be able to
```
docker pull docker/for-desktop-kernel:4.14.131-ec66b3fe27f97f1ff98c46e41f4404f76b17a856-amd64
```
which is the result of cloning this linuxkit branch: https://github.com/linuxkit/linuxkit/pull/3407 and building it with `make build_4.14.x` in the `kernel/` directory.

The "future proof" option sounds interesting -- I'll investigate.

**Comment by singe** [comment] 2019-09-10 16:52
That works, thanks @djs55. I didn't realise they were already published!

```
# cat /usr/src/linux-headers-4.14.131-linuxkit/include/generated/randomize_layout_hash.h 
#define RANDSTRUCT_HASHED_SEED "ab7e6491102cb1f0852ff1f47d43cfe4fcce0f1c4d18619210497a3a326f2314"
```

That should be enough to close this. @rvdh?

For my use-case, I just need to wait for docker-desktop to catch up to this linuxkit commit https://github.com/linuxkit/linuxkit/commit/315ddf88e22d52d3873ba7de73128c3f1d63e7e7

**Comment by rn** [comment] 2019-09-30 23:37
Closing this issue as this is not related to LinuxKit itself but related to the Docker Desktop, which does not seem to use the LinuxKit kernels.

**Closed by rn** 2019-09-30 23:37 UTC

**Comment by djs55** [comment] 2019-10-15 08:56
For reference I've made a PR to switch Docker Desktop back to the LinuxKit kernels again. Hopefully this will be in the next "edge" release.

**Comment by thebalaa** [comment] 2020-03-23 18:19
@djs55 hi David, it looks like this is happening again with the latest releases of Docker for Win/Mac. Could you point me to the kernel sources that will produce a module with the correct magic version string. I tried using the sources from the official linuxkit images and also all of the images from the repository you linked above. Thanks!

**Comment by djs55** [comment] 2020-03-23 19:20
@thebalaa sorry about that -- we took a couple of FUSE and `virtio-blk` back ports to the 4.19 series. I'm hoping to upgrade onto vanilla standard linuxkit 5.4 kernels again (although it looks like they're not working in Docker Desktop for some reason -- I'll have to investigate). 

I've linked to the docker image containing the kernel sources on [this comment](https://github.com/docker/for-win/issues/6099#issuecomment-602665387). Hopefully the headers in that image contain the correct `RANDSTRUCT_HASHED_SEED` etc.

Sorry again for the inconvenience!

**Comment by steigr** [comment] 2020-04-19 21:54
You can find the correct docker-for-desktop kernel image from /etc/linuxkit.yml in the docker-for-desktop's `docker.iso`.

I've written an utility to to extract the correct kernel image name: http://github.com/steigr/docker-for-desktop-get-kernel-image ( Docker-Image is available here: https://quay.io/steigr/docker-for-desktop-get-kernel-image:latest ) and run it like `docker run --rm --device=/dev/sr0 quay.io/steigr/docker-for-desktop-get-kernel-image:latest`. Then go ahead with the correct kernel-headers.
