### ISSUE TITLE
installing with `go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit` fails with a "invalid version: unknown revision 000000000000" message

### ISSUE THREAD

**Issue by jf** [linuxkit/linuxkit#3602] opened 2021-02-17 12:07 UTC
**Description**

Using `go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit` fails with the following result:

```
# go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
go: downloading github.com/linuxkit/linuxkit v0.0.0-20210215175756-1f93eab506c9
go: downloading github.com/linuxkit/linuxkit/src/cmd/linuxkit v0.0.0-20210215175756-1f93eab506c9
...
go: downloading github.com/prometheus/procfs v0.0.5
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/containerd/cgroups v0.0.0-20190919134610-bf292b21730f
go: downloading github.com/containerd/cgroups v0.0.0-20210114181951-8a68de567b68
go get: github.com/deislabs/oras@v0.8.1 updating to
        github.com/deislabs/oras@v0.10.0 requires
        github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Steps to reproduce the issue:**

On Ubuntu 20.04.2 LTS, with go version `go version go1.16 linux/amd64`, run `go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit`. Go is downloaded and installed from the tarball at https://golang.org/dl/ if that matters (but I don't think it does).

**Comment by deitch** [comment] 2021-02-17 13:04
The issue isn't linuxkit, which doesn't import oras directly, but manifest-tool, which does. The issue is [here](https://github.com/deislabs/oras/issues/211). At heart, it is because go modules respect `replace` commands in a `go.mod` file only when in the main file, but not in a transient dependency. So oras includes a replace, but since that is just included by something else, it is ignored. I don't agree with the design, but we have to work with what we have.

oras updated to fix that [here](https://github.com/deislabs/oras/pull/218), but the latest release is v0.10.0, which predates it by 2 days.

There are several ways to fix this, but the simplest is just a new release of oras. I will reach out to the maintainers.

**Comment by jf** [comment] 2021-02-17 14:23
got it. Thanks for the explanation and the notes; *and* the action to help resolve this!

**Comment by rn** [comment] 2021-05-03 21:21
Closing this as it seems to have been fixed

**Closed by rn** 2021-05-03 21:21 UTC
