### ISSUE TITLE
HVSock related crash with 17.05.0-rc1

### ISSUE THREAD

**Issue by simonferquel** [linuxkit/linuxkit#1616] opened 2017-04-13 09:11 UTC
Hi, lately http_conn_to has started to re-fail on Docker for Windows (with moby 17.05.0-rc1, maybe with previous versions to), but this time without a kernel panic.
Moby diags shows messages in /var/log/messages.sdout that seem to imply that proxy-vsockd is crashing on hv_sock related stuff:
```Apr 13 05:18:09 moby kernel: proxy-vsockd    D    0 27443      1 0x00000000
Apr 13 05:18:09 moby kernel:  00000000000188c0 ffff8d44301b7400 ffff8d43c3ac6080 ffff8d43e98ecf00
Apr 13 05:18:09 moby kernel:  ffff8d44007061c0 ffff8d443b8588c0 ffffffffb3845fde 0000000000000002
Apr 13 05:18:09 moby kernel:  ffff8d44007061c0 ffffae220387be40 ffffffffb3f075bc ffff8d44007061c0
Apr 13 05:18:09 moby kernel: Call Trace:
Apr 13 05:18:09 moby kernel:  [<ffffffffb3845fde>] ? __schedule+0x35f/0x43d
Apr 13 05:18:09 moby kernel:  [<ffffffffb384613a>] ? schedule+0x7e/0x87
Apr 13 05:18:09 moby kernel:  [<ffffffffb3846305>] ? schedule_preempt_disabled+0xa/0xb
Apr 13 05:18:09 moby kernel:  [<ffffffffb3847429>] ? __mutex_lock_slowpath+0xb6/0x13b
Apr 13 05:18:09 moby kernel:  [<ffffffffb38474c9>] ? mutex_lock+0x1b/0x2a
Apr 13 05:18:09 moby kernel:  [<ffffffffb38474c9>] ? mutex_lock+0x1b/0x2a
Apr 13 05:18:09 moby kernel:  [<ffffffffb362507d>] ? vmbus_hvsock_device_unregister+0x15/0x3a
Apr 13 05:18:09 moby kernel:  [<ffffffffb363a788>] ? __sk_destruct+0x21/0x133
Apr 13 05:18:09 moby kernel:  [<ffffffffb3839583>] ? hvsock_release+0x17/0x29
Apr 13 05:18:09 moby kernel:  [<ffffffffb3635aad>] ? sock_release+0x1a/0x6c
Apr 13 05:18:09 moby kernel:  [<ffffffffb3635b0d>] ? sock_close+0xe/0x11
Apr 13 05:18:09 moby kernel:  [<ffffffffb31f7475>] ? __fput+0xdd/0x17b
Apr 13 05:18:09 moby kernel:  [<ffffffffb30f5216>] ? task_work_run+0x64/0x7a
Apr 13 05:18:09 moby kernel:  [<ffffffffb3003285>] ? prepare_exit_to_usermode+0x7d/0x96
Apr 13 05:18:09 moby kernel:  [<ffffffffb3848bc4>] ? entry_SYSCALL_64_fastpath+0xa7/0xa9
```

And then a kworker crashes as well:
```Apr 13 05:20:12 moby kernel: kworker/0:2     D    0  1318      2 0x00000000
Apr 13 05:20:12 moby kernel: Workqueue: hv_vmbus_con vmbus_onmessage_work
Apr 13 05:20:12 moby kernel:  00000000000188c0 0000000000000000 ffff8d4437faa040 ffff8d443e9ded00
Apr 13 05:20:12 moby kernel:  ffff8d443a84cc80 ffff8d443b8188c0 ffffffffb3845fde 0000000000000002
Apr 13 05:20:12 moby kernel:  ffff8d443a84cc80 ffffae2204797ad0 ffff8d443f6f3128 0000000000000002
Apr 13 05:20:12 moby kernel: Call Trace:
Apr 13 05:20:12 moby kernel:  [<ffffffffb3845fde>] ? __schedule+0x35f/0x43d
Apr 13 05:20:12 moby kernel:  [<ffffffffb3847d81>] ? usleep_range+0x66/0x66
Apr 13 05:20:12 moby kernel:  [<ffffffffb384613a>] ? schedule+0x7e/0x87
Apr 13 05:20:12 moby kernel:  [<ffffffffb3847dc4>] ? schedule_timeout+0x43/0x101
Apr 13 05:20:12 moby kernel:  [<ffffffffb38469aa>] ? __wait_for_common+0x120/0x158
Apr 13 05:20:12 moby kernel:  [<ffffffffb38469aa>] ? __wait_for_common+0x120/0x158
Apr 13 05:20:12 moby kernel:  [<ffffffffb30ff0f9>] ? wake_up_q+0x45/0x45
Apr 13 05:20:12 moby kernel:  [<ffffffffb3624a1a>] ? vmbus_open+0x2a3/0x37e
Apr 13 05:20:12 moby kernel:  [<ffffffffb3839ffe>] ? hvsock_probe+0x137/0x26f
Apr 13 05:20:1

2 moby kernel:  [<ffffffffb3622643>] ? vmbus_probe+0x36/0x7e
Apr 13 05:20:12 moby kernel:  [<ffffffffb350288b>] ? driver_probe_device+0x10b/0x249
Apr 13 05:20:12 moby kernel:  [<ffffffffb3502a7c>] ? driver_allows_async_probing+0x29/0x29
Apr 13 05:20:12 moby kernel:  [<ffffffffb3500e7b>] ? bus_for_each_drv+0x7e/0xa2
Apr 13 05:20:12 moby kernel:  [<ffffffffb35026ea>] ? __device_attach+0xa6/0x11a
Apr 13 05:20:12 moby kernel:  [<ffffffffb3501d54>] ? bus_probe_device+0x2d/0x89
Apr 13 05:20:12 moby kernel:  [<ffffffffb35000e5>] ? device_add+0x2b6/0x50d
Apr 13 05:20:12 moby kernel:  [<ffffffffb3125984>] ? init_timer_key+0x13/0x2e
Apr 13 05:20:12 moby kernel:  [<ffffffffb3622b31>] ? vmbus_device_register+0x57/0x6e
Apr 13 05:20:12 moby kernel:  [<ffffffffb362554b>] ? vmbus_onoffer+0x47e/0x546
Apr 13 05:20:12 moby kernel:  [<ffffffffb301fd8b>] ? __switch_to+0x33a/0x480
Apr 13 05:20:12 moby kernel:  [<ffffffffb36225aa>] ? vmbus_onmessage_work+0x1b/0x25
Apr 13 05:20:12 moby kernel:  [<ffffffffb36225aa>] ? vmbus_onmessage_work+0x1b/0x25
Apr 13 05:20:12 moby kernel:  [<ffffffffb30f1d50>] ? process_one_work+0x185/0x287
Apr 13 05:20:12 moby kernel:  [<ffffffffb30f231a>] ? worker_thread+0x1d8/0x2ab
Apr 13 05:20:12 moby kernel:  [<ffffffffb30f2142>] ? rescuer_thread+0x2c4/0x2c4
Apr 13 05:20:12 moby kernel:  [<ffffffffb30f660d>] ? kthread+0xab/0xb3
Apr 13 05:20:12 moby kernel:  [<ffffffffb30f6562>] ? init_completion+0x1d/0x1d
Apr 13 05:20:12 moby kernel:  [<ffffffffb3848d95>] ? ret_from_fork+0x25/0x30
```

Attached is the full moby diags tar
[pinata.backend.network.http_conn_to.diag.tar.zip](https://github.com/docker/linuxkit/files/918994/pinata.backend.network.http_conn_to.diag.tar.zip)
cc @rneugeba

**Comment by rneugeba** [comment] 2017-05-09 09:20
what's the kernel version?

**Comment by rneugeba** [comment] 2017-05-15 09:21
The corresponding internal ticket was closed as it can't be reproduced anymore. @simonferquel can this be closed too?

**Comment by rneugeba** [comment] 2017-05-18 09:10
Closing because internal ticket is closed and requested info not supplied.

**Closed by rneugeba** 2017-05-18 09:10 UTC
Labels: kind/bug
