### ISSUE TITLE
logread v1.0 does not "-F"ollow 

### ISSUE THREAD

**Issue by danrzs** [linuxkit/linuxkit#4048] opened 2024-07-02 19:40 UTC
**Description**

logread in memlogd v1.0.0 does not appear to "-F"ollow (but will "-f"ollow) a given memlogd instance

**Steps to reproduce the issue:**

Consider the following dockerfile

```dockerfile
FROM linuxkit/memlogd:v0.8-amd64 AS memlogd-0.8
FROM linuxkit/memlogd:v1.0.0-amd64 AS memlogd-1.0

FROM alpine:3.19    

COPY --from=memlogd-1.0 /usr/bin/memlogd /usr/bin/memlogd
COPY --from=memlogd-0.8 /usr/bin/logread /usr/bin/logread-0.8
COPY --from=memlogd-1.0 /usr/bin/logread /usr/bin/logread-1.0
```

build it, run it in interactive, run the following:

```shell
memlogd &

logread-0.8 -F
logread-1.0 -F
```

**Describe the results you received:**
```
/ # memlogd &
...
/ # logread-0.8  -F
{"time":"2024-07-02T19:22:51.974497577Z","source":"memlogd","msg":"memlogd started"}
^C
/ # logread-1.0  -F
2024-07-02T19:22:51.974497577Z;memlogd;memlogd started
/ # 
```

**Describe the results you expected:**

note in the -0.8 version i had to ctrl c out - as expected the instance of logread was "-F"ollowing the memlogd logs
note in the 1.0 version i was returned to the command line  straight away - there was no "-F"ollow behaviour

**Additional information you deem important (e.g. issue happens only occasionally):**

maybe a different issue - the json log line is confusing me slightly: i thought this was supposed to be a custom ';'-separated format, as seen in the v1.0 logread? im happy if this is a thing as its more useful to my purposes. i had a check of the images with [dive](https://github.com/wagoodman/dive) and theres nothing else named logread (like, e.g. [busyboxes logread](https://boxmatrix.info/wiki/Property:logread)) that i could be mistakenly copying out there.

few other basic diagnostics:

```shell
/ # logread-0.8 -v
flag provided but not defined: -v
Usage of logread-0.8:
  -F	dump log, then follow
  -f	follow log buffer
  -socket string
    	memlogd log query socket (default "/var/run/memlogdq.sock")
/ # logread-1.0 -v
flag provided but not defined: -v
Usage of logread-1.0:
  -F	dump log, then follow
  -f	follow log buffer
  -socket string
    	memlogd log query socket (default "/var/run/memlogdq.sock")
/ # ls -lah $(which logread-0.8) $(which logread-1.0)
-rwxr-xr-x    1 root     root        2.5M May 10  2020 /usr/bin/logread-0.8
-rwxr-xr-x    1 root     root        1.8M Jan 28 19:40 /usr/bin/logread-1.0
```

**Comment by deitch** [comment] 2024-07-03 11:32
Looks like the issue is [here](https://github.com/linuxkit/linuxkit/blob/master/pkg/memlogd/cmd/logread/main.go#L44):

```go
	c, err := StreamLogs(socketPath, follow, dumpFollow)
```

The first arg is the socketPath, makes sense. The second is `follow bool` and the third is `dumpFollow bool`. But the signature is slightly different:

```go
func StreamLogs(socketPath string, follow, dump bool) (<-chan LogEntry, error)
```

Meaning whether or not to follow is second arg, and whether or not to dump is third arg. That combination of dump OR follow OR "dump and follow" should be resolved in the command handler before calling `StreamLogs`. I suspect it should be something like:

```go
	flag.StringVar(&socketPath, "socket", "/var/run/memlogdq.sock", "memlogd log query socket")
	flag.BoolVar(&dumpFollow, "F", false, "dump log, then follow")
	flag.BoolVar(&follow, "f", false, "follow log buffer")
	flag.Parse()

	if dumpFollow {
		follow = true
	}

	c, err := StreamLogs(socketPath, follow, dumpFollow)
```

Test it yourself and, if it works, open a PR?

**Comment by danrzs** [comment] 2024-07-03 12:36
That appears to have solved the issue :)

```shell
git clone git@github.com:linuxkit/linuxkit.git
cd linuxkit/pkg/memlogd
nano cmd/logread/main.go
# make the above edit
docker build -t logreadedit .
```

the test dockerfile now reads:
```dockerfile
FROM linuxkit/memlogd:v0.8-amd64 AS memlogd-0.8
FROM linuxkit/memlogd:v1.0.0-amd64 AS memlogd-1.0
FROM logreadedit AS memlogd-edit

FROM alpine:3.19    

COPY --from=memlogd-1.0 /usr/bin/memlogd /usr/bin/memlogd
COPY --from=memlogd-0.8 /usr/bin/logread /usr/bin/logread-0.8
COPY --from=memlogd-1.0 /usr/bin/logread /usr/bin/logread-1.0
COPY --from=memlogd-edit /usr/bin/logread /usr/bin/logread-edit
```

and repeating the above tests (including extra case for newest build)

```shell
/ # memlogd &
/ # 2024-07-03T12:28:54.983065534Z;memlogd;memlogd started

/ # logread-0.8 -F
{"time":"2024-07-03T12:28:54.983065534Z","source":"memlogd","msg":"memlogd started"}
^C
/ # logread-1.0 -F
2024-07-03T12:28:54.983065534Z;memlogd;memlogd started
/ # logread-edit -F
2024-07-03T12:28:54.983065534Z;memlogd;memlogd started
^C
```

Will get a PR together Soon(tm)

**Comment by danrzs** [comment] 2024-07-03 12:47
incidentally do you have any comment about the different formatting between the 0.8 and 1.0 builds of logread? 

at a brief perusal of [commits to memlogd/logread between 0.8 and 1.0](https://github.com/linuxkit/linuxkit/commit/0b136bf80d995f7ee3571a5347d890e705f48fb5) indicates  its due to memlogd-1.0 changing to sending json serialised logs - with logread-0.8 just dumping all text and logread-1.0 actually parsing the incoming json. do you concur with this? If so I'll probably open a small issue+pr to add a --json (or similar) flag as dumping the raw json would be really useful to me.

**Comment by deitch** [comment] 2024-07-03 12:51
[This](https://github.com/linuxkit/linuxkit/pull/3807) is the PR for that, about 2 years ago. This changes the format to be json and thus more standardized.

If you are looking for a way to have `logread` have alternative output formats, I don't see why not. As long as the default behaivour is unchanged, it should be fine.

**Comment by danrzs** [comment] 2024-07-03 13:33
ok thanks, put together and [issue](https://github.com/linuxkit/linuxkit/issues/4050) for that. a PR with your fix in is [ready](https://github.com/linuxkit/linuxkit/pull/4049)

**Closed** 2024-07-03 16:57 UTC
