### ISSUE TITLE
`linuxkit build` attempting to pull from Docker hub unnecessarily

### ISSUE THREAD

**Issue by jlindsey** [linuxkit/linuxkit#3634] opened 2021-04-22 17:17 UTC
**Description**

I have an image build that contains several custom packages. When testing locally, I build these packages with the `-dev` flag and then reference them in the image YAML accordingly (as `image: root/<whatever>:dev-amd64`).

Linuxkit reports that these packages exist in the local cache (via `linuxkit cache ls`); but when building an image containing them, it errors because it is still attempting to pull from Docker hub anyway.

**Steps to reproduce the issue:**
1. Have a simple valid package dir:
```shell
root@debian10:/linuxkit# tree pkg/smoketest/
pkg/smoketest/
├── build.yml
└── Dockerfile

0 directories, 2 files

root@debian10:/linuxkit# cat pkg/smoketest/build.yml
---
image: smoketest
arches: [amd64]

root@debian10:/linuxkit# cat pkg/smoketest/Dockerfile
FROM busybox
CMD ["echo", "hello"]
```
2. Build the package:
```shell
root@debian10:/linuxkit# linuxkit pkg build -dev pkg/smoketest/
Building "root/smoketest:dev"
No image pulled, continuing with build
Building for arch amd64 as root/smoketest:dev-amd64
No image pulled for arch amd64, continuing with build
building for platform linux/amd64 using builder linuxkit
[...]
Build complete, not pushing, all done.
```
3. Validate that the package is in the cache:
```shell
root@debian10:/linuxkit# linuxkit cache ls
image name                                                                       root manifest hash
root/smoketest:dev-amd64                                                         sha256:e08bd22942c70db9d4716bd09c2cb07e3bd76c69f534efbdf1fb129a194257bb
root/smoketest:dev                                                               sha256:4e3be9dd4ade71e20ed5085ddaf0bca4193efd63e43950a906e9e75cb7d168b6
```
4. Have an image YAML that uses the package:
```shell
root@debian10:/linuxkit# cat /tmp/base.yml
kernel:
  image: linuxkit/kernel:5.6.11
  cmdline: console=tty0
init:
- linuxkit/init:305e6125c5a36e175e6e97bb101579df72ef9fe0
- linuxkit/runc:v0.8
- linuxkit/containerd:a2aadac845a5e6eed869be5719f4be5c522ea602
onboot:
- name: dhcpcd
  image: linuxkit/dhcpcd:v0.8
  command:
  - /sbin/dhcpcd
  - -B
  - -f
  - /dhcpcd.conf
  - "-1"
services:
- name: tty
  image: linuxkit/getty:v0.8
  env:
  - INSECURE=true
- name: smoketest
  image: root/smoketest:dev-amd64
- name: acpid
  image: linuxkit/acpid:v0.8
```
5. Attempt to build  the image with `linuxkit build -format kernel+squashfs -dir build /tmp/base.yml`

**Describe the results you received:**
```shell
Extract kernel image: docker.io/linuxkit/kernel:5.6.11
Add init containers:
Process init image: docker.io/linuxkit/init:305e6125c5a36e175e6e97bb101579df72ef9fe0
Process init image: docker.io/linuxkit/runc:v0.8
Process init image: docker.io/linuxkit/containerd:a2aadac845a5e6eed869be5719f4be5c522ea602
Add onboot containers:
  Create OCI config for linuxkit/dhcpcd:v0.8
Add service containers:
  Create OCI config for linuxkit/getty:v0.8
  Create OCI config for root/smoketest:dev-amd64
FATA[0028] Could not pull image root/smoketest:dev-amd64: error getting manifest for trusted image docker.io/root/smoketest:dev-amd64: GET https://index.docker.io/v2/root/smoketest/manifests/dev-amd64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:root/smoketest Type:repository]]
```

**Describe the results you expected:**
A successful build pulling from the local cache at `/root/.linuxkit/cache`.

The tool should not attempt to pull packages from Docker hub unless the cache does not contain the package image or the `-pull` flag is passed to the `build` command

**Additional information you deem important (e.g. issue happens only occasionally):**
I attempted to circumvent this by building the packages into the local Docker image cache instead by passing the `-docker` flag to `pkg build`, but that resulted in a different error:

```
root@debian10:/linuxkit# linuxkit pkg build -dev -docker pkg/smoketest
Building "root/smoketest:dev"
No image pulled, continuing with build
Building for arch amd64 as root/smoketest:dev-amd64
No image pulled for arch amd64, continuing with build
building for platform linux/amd64 using builder linuxkit
[...]
open /var/lib/docker/tmp/docker-import-824914033/repositories: no such file or directory
exit status 1
```

**Comment by jlindsey** [comment] 2021-04-28 16:03
Researching this further, I believe this is partly a bug or regression, and partly a misunderstanding on my part.

From the docs:
> If you want to build images and test and run them *in a standalone* fashion locally, then you should add the docker image cache.

So I think the original complaint in this issue is not valid, though maybe the docs could be clarified a bit.

---

Therefore, the actual issue is in the "additional information" section above - saving to the docker cache for local standalone testing is broken. The underlying cause is that the implementation of `load` here: https://github.com/linuxkit/linuxkit/blob/b13b41b213a9b560fe7da437b66ee608d897d6a6/src/cmd/linuxkit/pkglib/docker.go#L370-L376

is calling `docker image load`, which expects an OCI bundle tar, but is being passed the output of `TarReader()` here: https://github.com/linuxkit/linuxkit/blob/b13b41b213a9b560fe7da437b66ee608d897d6a6/src/cmd/linuxkit/pkglib/build.go#L300-L309

which returns a flattened root filesystem tar, not an OCI bundle.

I believe the offending commit is c8ef7d0eb03ef592331fa24fc3045c8efd188fce.

I would be happy to submit a PR to help fix this, but I am not sure I'm familiar enough with the codebase to do the right thing.

**Comment by deitch** [comment] 2021-04-28 16:05
Yup, this definitely is an issue. There is an open PR #3638 to fix this. Can you confirm that this is your issue?

**Comment by jlindsey** [comment] 2021-04-28 17:07
@deitch Thanks for the response!

It seems to be somewhat my issue. I'm still unable to build into the docker cache by passing `-docker` to `pkg build`, but it seems like that PR is not intended to fix that.

But I still get "Could not pull image" errors when building packages locally, and I think after some experimentation with your branch that the issue is an erroneous cache miss.

Looking at the output of `build`, I can see eg:

```
Image docker.io/root/meta-handler:dev not found in local cache, pulling
```

and the output of `linuxkit cache ls` shows that all of the linuxkit and other docker hub-based images in my build are cached as `docker.io/linuxkit/containerd:...` or so, while all the ones I've built locally are simply `root/whatever:dev`.

If I go into `~/.linuxkit/cache/index.json` and manually update the `org.opencontainers.image.ref.name` annotation on my local packages to start with `docker.io/`, the cache is hit and my build succeeds.

**Comment by deitch** [comment] 2021-04-28 17:21
That PR addressed an issue where each `lkt pkg build` would think it was looking in cache, but in reality, it was just looking on the remote registry; in other words, a "cache missed it even exists". This adds that back correctly.

It sounds like this has a higher level issue, that once the basic "check the cache is in place", in certain image tagging/naming circumstances, it still does a miss?

if that is so, I would recommend that we get that one in (should be another day or two, awaiting #3637 getting merged first), then create exact steps to replicate it. Hopefully a small bug fix will hit it.

If that's not it, of course, then let's figure out what it is.

**Comment by jlindsey** [comment] 2021-04-28 17:32
> It sounds like this has a higher level issue, that once the basic "check the cache is in place", in certain image tagging/naming circumstances, it still does a miss?

Yes, I think that if I understand things correctly that there are two bugs in play here, and either one being fixed will solve my issue:

1. Trying to cache a custom local package in docker with `linuxkit pkg build -docker` fails due to https://github.com/linuxkit/linuxkit/issues/3634#issuecomment-828576612
2. Because of that, building an image that contains one of those packages with `linuxkit build` fails because it is not in the local Docker cache, and will always miss in the linuxkit cache (even though it exists there), and so will try to pull from docker hub (where it doesn't exist).

**Comment by deitch** [comment] 2021-04-29 08:50
Some things I don't understand here.

> Trying to cache a custom local package in docker with linuxkit pkg build -docker fails due to

`--docker` doesn't build in the docker image cache _instead_ of the linuxkit cache. It always builds into the linuxkit cache. What `--docker` does it tell it, when done building into linuxkit cache, to _also_ load it into docker image cache.

> building an image that contains one of those packages with linuxkit build fails because it is not in the local Docker cache

But `linuxkit build` does not look in the docker cache. It will look in the docker cache _first_ if you specify `--docker`, but that is just a "check here first and then look in linuxkit cache" instead of "go straight to linuxkit cache, and if not there, pull from registry".

Let's try to make this simpler for me. With the latest commit, can you confirm that the issue at the top still occurs?

**Comment by jlindsey** [comment] 2021-04-29 15:46
> Let's try to make this simpler for me. With the latest commit, can you confirm that the issue at the top still occurs?

Sure, I just tried it and I am still getting the error, yes. Some possibly helpful output:

```
root@debian10:/linuxkit# linuxkit cache ls
image name                                                                       root manifest hash
root/consul:dev                                                                  sha256:34a80cdd4d646988290899edcdabf950a42eeca4f9809e57d7ef81a69084abdb
docker.io/linuxkit/runc:v0.8                                                     sha256:6ce7c3967af2f711d13afa6f19e787dffdb69e29753d26c534bb6f193bbe8f79
docker.io/linuxkit/memlogd:v0.8                                                  sha256:2b73b4c86b5a54a417867fea942d79d52a98f8c08c5e4a4c3bc2b3c3e082fd4c
root/meta-handler:dev-amd64                                                      sha256:2b3330bcf7a812fdc228cb12bfab484a0712722db52d3f59bd48c8c797b5042e
root/nomad:dev                                                                   sha256:940b57b2aae431329b5620d8733b3f082f61d70631252c89a63b2752e7d3d00f
root/smoketest:dev-amd64                                                         sha256:e08bd22942c70db9d4716bd09c2cb07e3bd76c69f534efbdf1fb129a194257bb
docker.io/linuxkit/containerd:1ae8f054e9fe792d1dbdb9a65f1b5e14491cb106           sha256:c201adfb2436495072877c96bbb4b6e9b884a084b1d02915f841b88acac6794f
docker.io/linuxkit/sysctl:v0.8                                                   sha256:777807c08a2201853fb50594e3550ec183a3df4039ecee681a43ebe81aa2756a
root/consul:dev-amd64                                                            sha256:7073befc5a2c6a63ef494bdab5d3d648418607145983215c32ec4f23c73260a3
root/smoketest:dev                                                               sha256:ebd969c608eb1f0a79ccc5e1fed68efa8d4681a4ae4dda5df457aa3158c1b4fb
docker.io/linuxkit/kernel:5.4.113                                                sha256:561167abba8cb0c3efa2e2b8a0b5fedab7f9900078d8ead6fab7c72f1faab254
docker.io/linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c                 sha256:61113c18488f3e4bc28b0ad4674ab39b8fce930e6fb2fe9a1a1f8f09aa2b3c6d
docker.io/linuxkit/ca-certificates:v0.8                                          sha256:c0ca782444abfbe8f60cfdaa44cfe67a2fac9ee2e553325ef43cbc68c0c37721
docker.io/linuxkit/metadata:v0.8                                                 sha256:d19ebe28ca430e30730b6d81b471d64ecb7b589c47f165b0d31a9d0ec8b972f9
root/meta-handler:dev                                                            sha256:8eb7dad0855f7b1994422e033c859ccfed5b7232edfe5b03e9204a5a03e3beef
root/haveged:dev-amd64                                                           sha256:84fcced3bb1ad1d6ff07ce8c007a6f33493a6f93c3e4f70b1a0147ce3ed56169
root/haveged:dev                                                                 sha256:7e0b3fd0ca715bd7e0f706ff9a799bb0da98278b692c0c201f47ce63a9996abd
root/nomad:dev-amd64                                                             sha256:6afa115287f2c996dee18e36e7863d7ca3369c0fb518dacb841601293b1d018a
docker.io/linuxkit/sysfs:v0.8                                                    sha256:8a5f84582026d125f2e8ce85c1a475413b616f3d90051c3d9deb8a957d36bc21
```

```
root@debian10:/linuxkit# linuxkit build /tmp/consul.yml
...
INFO[0031]   Create OCI config for root/meta-handler:dev
DEBU[0031] ImagePull to cache docker.io/root/meta-handler:dev trusted reference docker.io/root/meta-handler:dev
INFO[0031] Image docker.io/root/meta-handler:dev not found in local cache, pulling
...
```

---

> But linuxkit build does not look in the docker cache. It will look in the docker cache first if you specify --docker, but that is just a "check here first and then look in linuxkit cache" instead of "go straight to linuxkit cache, and if not there, pull from registry".

I understand, which is why I believe there are two bugs in play:

1. There is an erroneous cache miss in the linuxkit cache that is causing it to attempt to pull a docker image that doesn't exist, failing the build
2. BUT, if I were able to use `--docker` in `build` and `pkg build` then that bug wouldn't affect me because it would miss the linuxkit cache, then pull from the local docker daemon.

Please let me know if there's any more info I can provide that would help!

**Comment by deitch** [comment] 2021-04-30 10:17
OK, I figured it out.

The problem is that `lkt pkg build`, when writing to the cache, takes the image name "as is". So if the image is `gcr.io/foo/bar:abc`, then it takes it, and if it is `docker.io/linuxkit/cool:beans`, then it takes it, and if it is `linuxkit/cool:beans`, then it takes it.

`lkt build`, on the other hand, when reading from cache, always canonicalizes the name. So `gcr.io/foo/bar:abc` will match, and `docker.io/linuxkit/cool:beans` will match, but if the original image was built as the short form `linuxkit/cool:beans`, then read will look for `docker.io/linuxkit/cool:beans` and it will miss.

To get this to be fixed, we need to:

* canonicalize the writes to cache during `lkt pkg build`
* canonicalize the read from cache during `lkt pkg build` (when it checks if the image already exists)

Then it all should be clean.

**Comment by deitch** [comment] 2021-04-30 12:07
@jlindsey try #3646 , build off that branch, see if it solves your problem. It did in all my runs.

**Closed** 2021-04-30 13:55 UTC
